// icon: file name inside public/img/stack icons
const stack: { name: string; icon: string }[] = [
  { name: 'TypeScript', icon: 'typescript.png' },
  { name: 'Node', icon: 'node.png' },
  { name: 'Express', icon: 'express.png' },
  { name: 'Nextjs', icon: 'nextjs.png' },
  { name: 'React', icon: 'react.svg' },
  { name: 'Docker', icon: 'docker.png' },
  { name: 'AWS', icon: 'aws.png' },
  { name: 'Azure', icon: 'azure.png' },
  { name: 'Firebase', icon: 'firebase.png' },
  { name: 'PostgreSQL', icon: 'postgresql.png' },
  { name: 'MySQL', icon: 'mysql.png' },
  { name: 'SQLServer', icon: 'sql-server.png' },
  { name: 'SQLite', icon: 'sqlite.png' },
  { name: 'MongoDB', icon: 'mongodb.png' },
  { name: 'Jira', icon: 'jira.png' },
  { name: 'Figma', icon: 'figma.png' },
  { name: 'Git', icon: 'git.png' },
  { name: 'GitHub', icon: 'github.png' },
  { name: 'Bitbucket', icon: 'bitbucket.png' },
  { name: 'CircleCI', icon: 'circleci.png' },
  { name: 'Python', icon: 'python.png' },
  { name: '.NET', icon: 'dotnet.png' },
  { name: 'Nestjs', icon: 'nestjs.svg' },
  { name: 'Ruby on Rails', icon: 'rails.png' },
  { name: 'TailwindCSS', icon: 'tailwindcss.png' },
  { name: 'Redux', icon: 'redux.png' },
  { name: 'Zustand', icon: 'zustand.png' },
  { name: 'Jest', icon: 'jest.png' },
  { name: 'Cypress', icon: 'cypress.svg' },
  { name: 'Testing Library', icon: 'testing-library.png' },
  { name: 'jQuery', icon: 'jquery.png' },
  { name: 'TanStack Query', icon: 'tanstack-query.png' },
  { name: 'Mongoose', icon: 'mongoose.png' },
  { name: 'Sequelize', icon: 'sequelize.png' },
  { name: 'Svelte', icon: 'svelte.png' },
  { name: 'GraphQL', icon: 'graphql.png' },
  { name: 'Apollo', icon: 'apollo.png' },
  { name: 'MaterialUI', icon: 'materialui.png' },
  { name: 'Sass', icon: 'sass.png' },
  { name: 'Bootstrap', icon: 'bootstrap.png' },
  { name: 'SemanticUI', icon: 'semanticui.png' },
];

export default stack;
